### ISSUE TITLE
Can't start project, `no-trailing-comma` rule is not found.

### ISSUE THREAD

**Issue by Grmiade** [ngrx/angular2-store-example#29]
I have this error when I run `npm start`:
```
ERROR in ./src/vendor.ts
Module build failed: Error: Could not find the following rules specified in the configuration:
no-trailing-comma
    at Object.loadRules (/Users/jeremyfauvel/Desktop/test/node_modules/tslint/lib/ruleLoader.js:29:15)
    at Linter.lint (/Users/jeremyfauvel/Desktop/test/node_modules/tslint/lib/tslint.js:26:44)
    at Object.lint (/Users/jeremyfauvel/Desktop/test/node_modules/tslint-loader/index.js:64:23)
    at Object.module.exports (/Users/jeremyfauvel/Desktop/test/node_modules/tslint-loader/index.js:126:8)

ERROR in ./src/main.ts
Module build failed: Error: Could not find the following rules specified in the configuration:
no-trailing-comma
    at Object.loadRules (/Users/jeremyfauvel/Desktop/test/node_modules/tslint/lib/ruleLoader.js:29:15)
    at Linter.lint (/Users/jeremyfauvel/Desktop/test/node_modules/tslint/lib/tslint.js:26:44)
    at Object.lint (/Users/jeremyfauvel/Desktop/test/node_modules/tslint-loader/index.js:64:23)
    at Object.module.exports (/Users/jeremyfauvel/Desktop/test/node_modules/tslint-loader/index.js:126:8)
```

**Comment by fxck** [comment]
yea it's outdated and should be deleted, try this one https://github.com/fxck/ngrx-example/

**Comment by Grmiade** [comment]
Thanks.

**Comment by MarkPieszak** [comment]
Change is in PR #30 once it gets Merged.

It was changed from `no-trailing-comma` to `trailing-comma` in tslint. Very strange breaking change they made (for almost no reason).
